org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=oxide
mod.name=Oxide
mod.group=com.ordana.oxide
mod.version=26.5.25-BETA
mod.description = Ashes to ashes, rust to rust
mod.homepage = https://modrinth.com/mod/oxide
mod.github = https://github.com/AstralOrdana/Oxide
mod.credits = Created by Ordana and Keyberries for Modfest 25, additional planning help from eldabys, texture assistance by derp_gamer22
mod.authors = Ordana, Keyberries, eldabys
mod.license = LGPLv3

deps.fabric-loader=0.19.5
deps.kaleido=0.3.3+1.3.2

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

publish.modrinth=mz1R5Wsg
publish.curseforge=
#publish.additionalVersions=